using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Budget_Buddy_App.Models;

namespace Budget_Buddy_App.Services
{
    public class ExportPdfService : IExportPdfService
    {
        public byte[] GeneratePdf(List<Transaction> transactions)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header().Text("Budget Buddy Report")
                        .FontSize(20)
                        .Bold()
                        .FontColor(Colors.Blue.Medium);

                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        // Table Header
                        table.Cell().Element(CellStyle).Text("Date").Bold();
                        table.Cell().Element(CellStyle).Text("Category").Bold();
                        table.Cell().Element(CellStyle).Text("Amount").Bold();
                        table.Cell().Element(CellStyle).Text("Note").Bold();

                        // Table Rows
                        foreach (var t in transactions)
                        {
                            table.Cell().Element(CellStyle).Text(t.Date.ToShortDateString());
                            table.Cell().Element(CellStyle).Text(t.Category?.Title ?? "");
                            table.Cell().Element(CellStyle).Text(t.Amount.ToString("C"));
                            table.Cell().Element(CellStyle).Text(t.Note ?? "");
                        }

                        static IContainer CellStyle(IContainer container)
                        {
                            return container
                                .PaddingVertical(5)
                                .PaddingHorizontal(10)
                                .BorderBottom(1)
                                .BorderColor(Colors.Grey.Lighten2);
                        }
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by Budget Buddy | ").FontSize(10);
                            x.CurrentPageNumber().FontSize(10);
                            x.Span(" / ").FontSize(10);
                            x.TotalPages().FontSize(10);
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}
